name: Deploy Frontend

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t jmadurga/miapp-frontend:latest .

      - name: Push Docker image
        run: |
          docker push jmadurga/miapp-frontend:latest

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DO_ACCESS_TOKEN }}

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Fetch kubeconfig from DO
        run: |
          doctl kubernetes cluster kubeconfig save "${{ secrets.DO_K8S_CLUSTER_NAME_OR_ID }}"
          kubectl config current-context
          kubectl get nodes


     
      - name: Update image and rollout
        run: |
          kubectl set image deployment/frontend-deployment frontend=jmadurga/miapp-frontend:latest --record
          kubectl rollout status deployment/frontend-deployment --timeout=120s
